import { useEffect, useState } from "react";
import Navbar from "./Navbar";
import { foodApi, orderApi } from "../services/api";

const initialFood = { name: "", price: "", category: "Pizza", description: "", image: "", isVeg: true, isAvailable: true };
const statuses = ["Pending", "Preparing", "Out for Delivery", "Delivered", "Cancelled"];

export default function Admin() {
  const [foods, setFoods] = useState([]); const [orders, setOrders] = useState([]); const [form, setForm] = useState(initialFood);
  const [editingId, setEditingId] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { const [foodData, orderData] = await Promise.all([foodApi.list(), orderApi.all()]); setFoods(foodData.item || []); setOrders(orderData.orders || []); };
  useEffect(() => { load().catch((requestError) => setError(requestError.message)); }, []);
  const change = (event) => { const { name, value, type, checked } = event.target; setForm((current) => ({ ...current, [name]: type === "checkbox" ? checked : value })); };
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const payload = { ...form, price: Number(form.price) }; if (editingId) await foodApi.update(editingId, payload); else await foodApi.add(payload); setMessage(editingId ? "Food updated." : "Food added."); setEditingId(""); setForm(initialFood); await load(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const edit = (food) => { setEditingId(food._id); setForm({ name: food.name, price: food.price, category: food.category, description: food.description, image: food.image, isVeg: food.isVeg, isAvailable: food.isAvailable }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const seedMenu = async () => { setError(""); try { const result = await foodApi.seed(); setMessage(result.message); await load(); } catch (requestError) { setError(requestError.message); } };
  const remove = async (id) => { if (!window.confirm("Delete this food item?")) return; try { await foodApi.remove(id); setMessage("Food deleted."); await load(); } catch (requestError) { setError(requestError.message); } };
  const updateStatus = async (id, status) => { try { await orderApi.updateStatus(id, status); await load(); } catch (requestError) { setError(requestError.message); } };
  return <div className="min-h-screen bg-slate-50"><Navbar /><main className="mx-auto max-w-7xl px-4 pb-16 pt-28"><h1 className="text-3xl font-extrabold text-slate-900">Admin <span className="text-orange-500">Dashboard</span></h1>{message ? <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">{message}</p> : null}{error ? <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}
    <section className="mt-8 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">{editingId ? "Edit food" : "Add food"}</h2><form onSubmit={submit} className="mt-4 grid gap-3 md:grid-cols-2"><input required name="name" value={form.name} onChange={change} placeholder="Food name" className="rounded-xl border p-3"/><input required min="1" type="number" name="price" value={form.price} onChange={change} placeholder="Price" className="rounded-xl border p-3"/><input required name="category" value={form.category} onChange={change} placeholder="Category" className="rounded-xl border p-3"/><input required type="url" name="image" value={form.image} onChange={change} placeholder="Image URL" className="rounded-xl border p-3"/><textarea required name="description" value={form.description} onChange={change} placeholder="Description" className="rounded-xl border p-3 md:col-span-2"/><label className="flex gap-2 text-sm"><input type="checkbox" name="isVeg" checked={form.isVeg} onChange={change}/> Vegetarian</label><label className="flex gap-2 text-sm"><input type="checkbox" name="isAvailable" checked={form.isAvailable} onChange={change}/> Available</label><div className="flex gap-3 md:col-span-2"><button disabled={saving} className="rounded-xl bg-orange-500 px-5 py-3 text-sm font-bold text-white">{saving ? "Saving…" : editingId ? "Update food" : "Add food"}</button>{editingId ? <button type="button" onClick={() => { setEditingId(""); setForm(initialFood); }} className="text-sm font-bold text-slate-600">Cancel</button> : null}</div></form></section>
    <section className="mt-8"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">Menu management</h2>{foods.length === 0 ? <button onClick={seedMenu} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white">Add starter menu</button> : null}</div><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{foods.map((food) => <article key={food._id} className="overflow-hidden rounded-2xl bg-white shadow-sm"><img src={food.image} alt="" className="h-32 w-full object-cover"/><div className="p-4"><p className="font-bold">{food.name}</p><p className="text-sm text-slate-500">₹{food.price} · {food.isAvailable ? "Available" : "Unavailable"}</p><div className="mt-3 flex gap-4 text-sm font-bold"><button onClick={() => edit(food)} className="text-orange-500">Edit</button><button onClick={() => remove(food._id)} className="text-red-600">Delete</button></div></div></article>)}</div></section>
    <section className="mt-8"><h2 className="text-xl font-bold">Order management</h2><div className="mt-4 overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-100 text-slate-600"><tr><th className="p-4">Order</th><th>Items</th><th>Total</th><th>Status</th></tr></thead><tbody>{orders.map((order) => <tr key={order._id} className="border-t"><td className="p-4">#{order._id.slice(-6).toUpperCase()}</td><td>{order.items.map((item) => `${item.quantity}× ${item.name}`).join(", ")}</td><td>₹{order.totalPrice}</td><td><select aria-label="Order status" value={order.status} onChange={(event) => updateStatus(order._id, event.target.value)} className="rounded-lg border p-2">{statuses.map((status) => <option key={status}>{status}</option>)}</select></td></tr>)}</tbody></table></div></section>
  </main></div>;
}
